[build]
  base = "vite-project"
  publish = "dist"
  command = "CI= npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 